#!/usr/bin/env bash
# Export the already-built podman image into the two artifacts.
# The image (localhost/frame-algorithm:1.0) was built successfully; only the
# export steps need re-running.
#
#   ssh cpu34
#   tmux new -s export      # recommended: each export moves ~18 GB
#   bash /home/ajenane/orena/orena_submission/export_artifacts.sh
#
# NOTE: do not edit this file while it is running (NFS stale file handle).
set -euo pipefail

TAG=localhost/frame-algorithm:1.0
STAMP=$(date +%Y-%m-%d_%H-%M-%S)
OUT_DIR=/home/ajenane/orena/orena_submission
SIF=$HOME/images/frame-algorithm-${STAMP}.sif
TARGZ=$OUT_DIR/frame-algorithm_${STAMP}.tar.gz
LOG=$OUT_DIR/export_${STAMP}.log

exec > >(tee -a "$LOG") 2>&1
echo "logging to $LOG"
echo "started $(date)"

podman image exists "$TAG" || { echo "FATAL: image $TAG not found (podman images)"; exit 1; }
podman images --filter reference="$TAG" --format '{{.Repository}}:{{.Tag}}  {{.Size}}'
df -h / | tail -1

echo
echo "=== 1/2 submission artifact: docker-archive .tar.gz ==="
podman save --format docker-archive "$TAG" | gzip > "$TARGZ"
ls -lh "$TARGZ"

echo
echo "=== 2/2 test artifact: .sif for apptainer ==="
if command -v apptainer >/dev/null; then
    mkdir -p "$HOME/images"
    TMP_OCI=/tmp/${USER}-fa-oci-${STAMP}.tar
    podman save --format oci-archive -o "$TMP_OCI" "$TAG"
    apptainer build "$SIF" "oci-archive:$TMP_OCI"
    rm -f "$TMP_OCI"
    ls -lh "$SIF"
else
    echo "apptainer not found -- skipping .sif"
fi

echo
echo "=== done $(date) ==="
echo "  submit : $TARGZ"
echo "  test   : $SIF"
echo "  log    : $LOG"
echo
echo "Verify CUDA inside the shipped image on an H200 (NOT the RTX PRO 6000 --"
echo "that is Blackwell sm_120, unsupported by this image's CUDA 12.4 torch):"
echo
echo "  srun -p gpu-large -w gpu38 --gres=gpu:h200:1 --time=00:20:00 \\"
echo "    apptainer exec --nv $SIF \\"
echo "    python -c \"import torch;print(torch.__version__,torch.version.cuda,torch.cuda.is_available(),torch.cuda.get_device_name(0))\""
echo
echo "Then a full 3-question batch through the real entrypoint:"
echo "  mkdir -p /tmp/fa-output && srun -p gpu-large -w gpu38 --gres=gpu:h200:1 --time=00:30:00 \\"
echo "    apptainer run --nv \\"
echo "      --bind $OUT_DIR/frame-algorithm/test/input/interface_1:/input:ro \\"
echo "      --bind /tmp/fa-output:/output \\"
echo "      $SIF && cat /tmp/fa-output/answer.json"
